### ISSUE TITLE
Syntax error, and make sure /etc/auto.master.d exists

### ISSUE THREAD

**Issue by mok0** [sedunne/ansible-role-autofs#1]
Hi, I got a warning from Ansible:

```
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ autofs_allow_browse == True }}
```
it worked when I changed it the line in `tasks/config.yml` to:

```
when: autofs_allow_browse == True
```

I also had the problem that the role failed because the directory `/etc/auto.master.d` did not exist. I enclose a patch containing these two fixes. Thanks for your work!
[patch.txt](https://github.com/sedunne/ansible-role-autofs/files/2966926/patch.txt)

**Comment by sedunne** [comment]
Hey @mok0 thanks for the patch. I'll have a look and merge it in later today if it looks good!

**Comment by sedunne** [comment]
I've merged in the patch, and thanks again for submitting it! I'll have an updated version pushed to Galaxy soon ™️ . For now, using the master branch or commit hash in your requirements file should work.
